# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Translator(object):
    def setupUi(self, Translator):
        Translator.setObjectName("Translator")
        Translator.resize(1004, 732)
        font = QtGui.QFont()
        font.setPointSize(13)
        Translator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Translator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.target_plaintext = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.target_plaintext.setFont(font)
        self.target_plaintext.setObjectName("target_plaintext")
        self.gridLayout.addWidget(self.target_plaintext, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.target_language_combo = QtWidgets.QComboBox(self.centralwidget)
        self.target_language_combo.setObjectName("target_language_combo")
        self.target_language_combo.addItem("")
        self.target_language_combo.addItem("")
        self.horizontalLayout.addWidget(self.target_language_combo, 0, QtCore.Qt.AlignLeft)
        self.translator_button = QtWidgets.QPushButton(self.centralwidget)
        self.translator_button.setObjectName("translator_button")
        self.horizontalLayout.addWidget(self.translator_button, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.source_language_combo = QtWidgets.QComboBox(self.centralwidget)
        self.source_language_combo.setObjectName("source_language_combo")
        self.source_language_combo.addItem("")
        self.source_language_combo.addItem("")
        self.source_language_combo.addItem("")
        self.gridLayout.addWidget(self.source_language_combo, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.source_plaintext = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.source_plaintext.setFont(font)
        self.source_plaintext.setPlainText("")
        self.source_plaintext.setObjectName("source_plaintext")
        self.gridLayout.addWidget(self.source_plaintext, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.ApiKey_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ApiKey_lineEdit.setObjectName("ApiKey_lineEdit")
        self.horizontalLayout_3.addWidget(self.ApiKey_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 2, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.BaseURL_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.BaseURL_lineEdit.setObjectName("BaseURL_lineEdit")
        self.horizontalLayout_4.addWidget(self.BaseURL_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 2, 1)
        Translator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Translator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 24))
        self.menubar.setObjectName("menubar")
        Translator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Translator)
        self.statusbar.setObjectName("statusbar")
        Translator.setStatusBar(self.statusbar)

        self.retranslateUi(Translator)
        QtCore.QMetaObject.connectSlotsByName(Translator)

    def retranslateUi(self, Translator):
        _translate = QtCore.QCoreApplication.translate
        Translator.setWindowTitle(_translate("Translator", "AI翻译"))
        self.target_language_combo.setItemText(0, _translate("Translator", "中文"))
        self.target_language_combo.setItemText(1, _translate("Translator", "English"))
        self.translator_button.setText(_translate("Translator", "翻译"))
        self.source_language_combo.setItemText(0, _translate("Translator", "自动"))
        self.source_language_combo.setItemText(1, _translate("Translator", "中文"))
        self.source_language_combo.setItemText(2, _translate("Translator", "English"))
        self.source_plaintext.setPlaceholderText(_translate("Translator", "请输入待翻译的文字"))
        self.label.setText(_translate("Translator", "api key"))
        self.ApiKey_lineEdit.setPlaceholderText(_translate("Translator", "请输入openai的apikey"))
        self.label_2.setText(_translate("Translator", "BaseURL"))
        self.BaseURL_lineEdit.setText(_translate("Translator", "https://api.openai.com/v1"))
